version: '3'
services:
  db:
    image: postgres:13.0
    container_name: uzcolletest-db
    restart: always
    ports:
      - '5434:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
  bundle:
  node_modules:
  tmp:
